apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:  
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend 
        image: ashishkumart/expense-backend:v1 # Your built image
        ports:
          - containerPort: 5000
        env:
        - name: MONGODB_URI
          value: "mongodb://mongodb:27017/expense_tracker"
        - name: PORT
          value: "5000"

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:     
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000